version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
     build: .
     environment:
       AIRFLOW__CORE__EXECUTOR: LocalExecutor
       AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
     depends_on:
       - postgres
     command: >
       airflow db init && 
       airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin
     volumes:
       - ./dags:/usr/local/airflow/dags

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
    command: airflow webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
    ports:
      - "8080:8080"

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-init
    command: airflow scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags

  airflow-worker:
    build: .
    depends_on:
      - airflow-init
    command: celery worker
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
    volumes:
      - ./dags:/usr/local/airflow/dags

volumes:
  postgres-db-volume: